export const GET_BLOGS = "GET_BLOGS";
export const BLOGS_SUCCESS = "BLOGS_SUCCESS";
export const BLOGS_FAILURE = "BLOGS_FAILURE";

export const GET_FILTERED_BLOGS = "GET_FILTERED_BLOGS";

export const GET_BLOG = "GET_BLOG";
export const BLOG_SUCCESS = "BLOG_SUCCESS";
export const BLOG_FAILURE = "BLOG_FAILURE";

export const GET_SEARCH_BLOGS = "GET_SEARCH_BLOGS";
export const SEARCH_BLOGS_SUCCESS = "SEARCH_BLOGS_SUCCESS";
export const SEARCH_BLOGS_FAILURE = "SEARCH_BLOGS_FAILURE";

export const GET_CATEGORY_BLOGS = "GET_CATEGORY_BLOGS";
export const GET_CATEGORY_BLOGS_SUCCESS = "GET_CATEGORY_BLOGS_SUCCESS";
export const GET_CATEGORY_BLOGS_FAILURE = "GET_CATEGORY_BLOGS_FAILURE";

export const POST_BLOG = "POST_BLOG";
export const POST_BLOG_SUCCESS = "POST_BLOG_SUCCESS";
export const POST_BLOG_FAILURE = "POST_BLOG_FAILURE";

export const DELETE_BLOG = "DELETE_BLOG";

export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_FAILURE = "GET_COMMENT_FAILURE";

export const EDIT_POST = "EDIT_POST";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_FAILURE = "EDIT_POST_FAILURE";
